### ISSUE TITLE
Feedback/Kontakt zum Serverbetreiber

### ISSUE THREAD

**Issue by s72785** [jklmnn/ParkenDD#1]
Der Kontakt zum Server-Betreiber könnte wichtig werden, es wäre schön wenn hierzu nicht groß gesucht werden müsste, sondern Feedback direkt aus der App möglich würde.

**Comment by jklmnn** [comment]
Momentan wird erst mal eine Mailaddresse der Serverbetreibers angezeigt.

**Comment by jklmnn** [comment]
Serververwaltung über OpenData Community. Closed, siehe #7
