### ISSUE TITLE
Tschechische Übersetzung

### ISSUE THREAD

**Issue by balzer82** [jklmnn/ParkenDD#10]
Die App interessiert sicherlich auch viele Tschechen, die nach Dresden shoppen kommen

**Comment by jklmnn** [comment]
Da muss mir allerdings jemand helfen, da ich außer ahoi kein Tschechisch kann ;)

**Comment by balzer82** [comment]
Ich kenne jemanden, der das könnte. Wie aber praktisch realisieren?

Kannst du eine language.csv erstellen, wo z.B. das deutsche Wort, dann das englische und dann das Tschechische drin steht und je nach Sprachwahl in der App wird 1., 2. oder 3. gewählt? Achtung auch wegen der utf-8 Sache. Weiß nicht ob alle Tschechischen Laute damit definiert sind.

Die Datei könnte ich dann verschicken und um Übersetzung beten. Oder hast du eine bessere Idee?


Am Freitag, 13. März 2015 um 08:51 schrieb jklmnn:

**Comment by jklmnn** [comment]
In Android Apps gibt es eine strings.xml in der alle String drin stehen sollen. Die ist genau für so was gedacht. Du musst also nur die strings.xml nehmen und übersetzen. Allerdings muss ich noch mal schauen, wie man das mit mehreren Sprachen in der selben App macht.
Beispiel, die aktuelle strings.xml: https://github.com/jklmnn/ParkenDD/blob/master/app/src/main/res/values/strings.xml

**Comment by jklmnn** [comment]
Also, ich hab mir das mal angeschaut. Eigentlich muss nur die strings.xml in values-cs ausgefüllt werden (am besten mit Hilfe der deutschen und englischen Datei) und dann als Pull-Request zurück geben.
Die leere tschechische strings.xml ist hier: https://github.com/jklmnn/ParkenDD/blob/master/app/src/main/res/values-cs/strings.xml

**Comment by balzer82** [comment]
Thanks to Radka Knösche

**Comment by balzer82** [comment]
Wie ist es mit der iOS App?

**Comment by kiliankoe** [comment]
> Wie ist es mit der iOS App?

Die ist aktuell auch nur Deutsch und Englisch. Bekommt aber noch ein paar UI Updates bevor ich die Lokalisierung nochmal anpasse. Weitere Lokalisierungen sind dann natürlich auch gerne gesehen! :grin:

**Comment by jklmnn** [comment]
Die Übersetzung ist mit 68cb7f24e0a0c60f029445b40373981874b2bfd2 drin, und ich hoffe, dass ich kdas kommende Woche rausbringen kann.

**Comment by jklmnn** [comment]
Habs doch schon released ;) https://github.com/jklmnn/ParkenDD/releases/tag/v0.5.0
Sollte morgen oder übermorgen bei F-Droid auftauchen.

**Comment by jklmnn** [comment]
Es sind in 12ad29c08077b052c35158c5091007bfe30a12e5 neue Strings hinzugekommen, kannst du die wieder übersetzen lassen? Die Strings stehen in https://github.com/jklmnn/ParkenDD/blob/master/app/src/main/res/values-cs/strings.xml mit Beschreibung drin.

**Comment by kiliankoe** [comment]
Da du deine Strings ja schon auf POEditor reingehauen hast, können wir doch direkt darauf verweisen^^

https://poeditor.com/projects/view?id=31080

**Comment by jklmnn** [comment]
Ja, da müssen wir uns noch mal zusammen setzen ;)

**Comment by jklmnn** [comment]
So das klappt soweit und ist jetzt work in progress.
