### ISSUE TITLE
Vorhersage der Parkhausbelegung

### ISSUE THREAD

**Issue by balzer82** [jklmnn/ParkenDD#12]
Ich habe beispielhaft für die Centrum-Galerie für das Jahr 2015 eine [Vorhersage der Belegung](http://mechlab-engineering.de/2015/03/vorhersage-der-parkhausbelegung-mit-offenen-daten/) (in %) mit Machine Learning entwickelt. Das könnte man als Experimental-Feature in die App einbauen.

Ich stelle mir so eine Art Slider vor, wenn man auf die Centrum-Galerie geht, wo man
|======+30min=======in 1h=========in 2h=========in 3h==..
und auch 
`am 18.08.2015 um 15Uhr`
über ein Date-Picker Tool in Android eingeben kann und dann die Belegung von der App zurück bekommt. Dazu müsste im einfachsten Fall [eine .CSV](http://mechlab-engineering.de/downloads/Centrum-Galerie-Belegung-Vorhersage-2015.csv) geparsed werden und der korrekte Wert daraus entnommen und angezeigt.

**Comment by jklmnn** [comment]
Ich würde dir Vorhersage gern in eine extra Activity auslagern (man würde im Action-Menü auf Vorhersage gehen und sich dort die Belegungen mit Slider und/oder Datepicker anschauen), da sich das zum testen sehr viel leichter auch wieder entfernen lässt. Wenn wir beschließen, das als festes Feature einzubauen wäre das etwas anderes. Aber ich denke, nur zum testen wäre dieser Grad der Integration zu hoch.
Ist das ok?

**Comment by balzer82** [comment]
Absolut! Wie du willst.

**Comment by jklmnn** [comment]
Also das Parsen funktioniert schon mal, allerdings ist die Performance ziemlich schlecht. Sollte das ein festes Feature werden bin ich dafür, das Datum zum Server zu schicken und/oder ein bisschen Caching zu betreiben.

**Comment by balzer82** [comment]
API ist natürlich angedacht. Würde ich aber auf gleichem Server implementieren, wo auch schon die bisherigen Daten bereitgestellt werden.
Das ist aber nicht meiner. Wird schon...

**Comment by jklmnn** [comment]
Also, ich habe es endlich geschafft, ab v0.6.0-test kann man sich die Belegung für die Centrum-Galerie anzeigen lassen. Das Laden dauert lange, und das Design ist auch nicht das beste, aber das Prinzip funktioniert.

**Comment by kiliankoe** [comment]
Haste mal nen Screenshot? Würde mich interessieren wie du die UI hingelegt hast.

**Comment by jklmnn** [comment]
Eigentlich hab ich nur nen Datepicker, nen Timepicker, ein Label und ne Ratingbar untereinander geklatscht ^^

**Comment by kiliankoe** [comment]
Dann muss ich halt mal wieder ein Android Gerät aus der Schublade kramen damit ich mir das anschauen kann :D

**Comment by balzer82** [comment]
Hab auch keins. Bitte Screenshot oder Screencast. :)

**Comment by jklmnn** [comment]
Sieht momentan so aus: http://jkliemann.de/parkendd/media/parkendd-pre-test.png

**Comment by jklmnn** [comment]
@balzer82 was mir aufgefallen ist, ist dass eine Genauigkeit von 15 MInuten nicht so viel Sinn macht, da die meisten Daten da keine Änderung. Wäre es möglich, die Genauigkeit der Vorhersage auf 1h zu senken? Ich denke, man könnte damit einen erheblichen Performancegewinn erreichen.

**Comment by balzer82** [comment]
Done. Hier die [.CSV mit stündlicher Auflösung](http://mechlab-engineering.de/downloads/Centrum-Galerie-Belegung-Vorhersage-2015.csv) und gerundet auf `int`.

**Comment by jklmnn** [comment]
Wow, so schnell hätte ich nicht damit gerechnet ^^
Eigentlich war das als Idee für die stabile Version gedacht ;)
Ich mache mir momentan noch einige Gedanken, wie man die Daten am sinnvollsten verwaltet, soll heißen, welche und wie viele Daten lokal gespeichert/gecached bzw. vom Server abgerufen werden.

**Comment by balzer82** [comment]
Am liebsten würde ich mich mal mit dir zusammen setzen und das Modell auf deinem Server implementieren, sodass es ne API gibt dafür.
Diese `parse_csv` Sache ist ja nur als Schnellschuss als Demonstrator gedacht. Ideal wäre es ja, wenn man so eine Vorhersage für alle Parkhäuser in der Stadt aufstellt und dann richtig als Feature implementiert. Allerdings ist das Machine Learning für viele sehr aufwändig!!
Thema Kongresszentrum oder Messe oder sowas. Da brauch man die Veranstaltungspläne und müsste auch die Beliebtheit der Messe/Künstler wissen usw., da wird es vielleicht nie funktionieren.
Auch solche Phänomene wie die Pegida Demos beeinflussen enorm. Das kann man schlecht abbilden vorab. Deshalb hatte ich erst mal die Centrum-Galerie gewählt, weil die relativ vorhersehbar funktioniert.

Jetzt ist das Ziel erstmal Marketing damit zu machen, damit wir die Beteiligten der Stadt dafür sensibilisieren, dass das gut ist, wenn man Daten maschinenlesbar frei gibt, weil eben sowas gutes damit angestellt werden kann. Weiter würde ich den Aufwand vorerst nicht treiben.

**Comment by balzer82** [comment]
Falls es für Android hilfreicher/schneller ist: [Centrum-Galerie-Belegung-Vorhersage-2015.db](http://mechlab-engineering.de/downloads/Centrum-Galerie-Belegung-Vorhersage-2015.db) als sqlite.

**Comment by kiliankoe** [comment]
Gerade mal endlich von F-Droid runtergeladen. Sicher, dass die Daten aus der CSV so stimmen? Oder ich versteh die Sterne so gar nicht :D

Beispiel:
04.05. 9:30 Uhr -> laut CSV 64% sind bei dir 3,5 Sterne
05.07. 9:30 Uhr -> laut CSV 34% sind bei dir 3 Sterne

**Comment by jklmnn** [comment]
Also bei mir sind beim 4.5.15 9:30 2 Sterne, und in der csv stehen 60% (also sind 40% frei -> 2 Sterne) und am 5.7. sind es 3 Sterne mit 40% in der csv.
Welche csv nimmst du denn, in meiner stehen gar keine Angaben genauer als 10% drin.

**Comment by kiliankoe** [comment]
Beim Versuch das zu screenshotten bekomm' ich auf Anhieb 2 Sterne, aber wenn ich zum 5. Mai wechsel und wieder zurück zum 4. sind es 3,5. Liegt wohl daran, was auch immer das für ein Bug ist^^

Was die CSV angeht... Ich meinte eigentlich die von Pauls Server genommen zu haben. Nur hab ich Floats, die ich wenn ich dort jetzt reinschaue nicht mehr sehe :D
```
...
2015-05-01 06:00:00,15.0
2015-05-01 06:15:00,15.0
2015-05-01 06:30:00,15.0
2015-05-01 06:45:00,15.375
2015-05-01 07:00:00,15.75
2015-05-01 07:15:00,16.125
2015-05-01 07:30:00,16.625
2015-05-01 07:45:00,17.125
2015-05-01 08:00:00,17.625
2015-05-01 08:15:00,18.375
2015-05-01 08:30:00,19.125
2015-05-01 08:45:00,19.5
2015-05-01 09:00:00,19.875
2015-05-01 09:15:00,20.25
2015-05-01 09:30:00,20.5
2015-05-01 09:45:00,20.75
...
```

So sieht meine aus^^

**Comment by jklmnn** [comment]
Ich hab die in meiner App, die hatte Paul ganz am Anfang verlinkt:
https://github.com/jklmnn/ParkenDD/blob/master/app/src/main/res/raw/forecast.csv

**Comment by jklmnn** [comment]
Ach Mist, ich weiß was ich vergessen hab, wenn du die Uhrzeit änderst, wird ein Date mit Datum und Zeit erstellt, wenn du aber das Datum änderst, wird eins mit Datum und 0:00 erstellt.
Ich hatte das gemacht, weil ich die Zeit erst nachher gemacht hab, hab dann aber vergessen, das zu ändern.

**Comment by kiliankoe** [comment]
Jo, von dort (bzw dem Issue in meinem Repo) dachte ich die zu haben. Aber der Link geht ja eh nach extern, daher unterstelle ich Paul jetzt einfach mal die Daten dort mal ausgetauscht zu haben! :D Wüsste sonst gerade nicht, wo die herkommen^^ Aber tut ja auch nicht so viel zur Sache, ist ja eh temporär.

**Comment by jklmnn** [comment]
Also zumindest die mit stündlicher Belegung und Int-Auflösung besitzt den selben Link, wie die, die ganz oben verlinkt ist, und die hab ich eigentlich genommen, also ist die glaub getauscht.
Was die Daten selbst betrifft, denke ich nicht, dass ein float Sinn macht.

**Comment by kiliankoe** [comment]
Genauigkeit auf die dritte Nachkommastelle ist für die Vorhersage sicherlich Quatsch^^ Ist mir jedoch relativ egal, läuft ja auch so. Aber das sind Dinge, die man beim Basteln der API dann nochmal anschauen kann. Für das experimentelle Feature jetzt gerade haut's ja so wie's ist schon mal ganz gut hin.

**Comment by balzer82** [comment]
Hab das Machine Learning Modell von RandomForest auf DecisionTreeRegressor umgestellt und daraus ergibt sich, dass ersteres nur auf 10% genau schätzt (wie im Blogbeitrag und auch die ursprüngliche CSV) und letzteres eine Regression ist, also beliebig viele Kommastellen, die allerdings keinen Sinn machen und deshalb auf int gerundet.
Die CSV hat sich also geändert, ja.

Sorry für die Verwirrung!

tl;dr Es ist jetzt besser mit der aktuellen CSV vom Server

**Comment by jklmnn** [comment]
Ich glaube, ich werde die aktuellen Daten bei Gelegenheit mit einbauen, und auch noch mal mein Interface überarbeiten.

**Comment by jklmnn** [comment]
Ich hab die neue Datei eingebaut und den Bug von Kilian gefixt. Die Sterne zeigen allerdings trotzdem noch eine Auflösung von 10% an.
Ich hab mal bissel gegoogled und mir überlegt, ein ExpandableListView zu nutzen (das beim Anklicken noch in der Liste Detailinformationen liefert) und da einen 24h Graphen reinzupacken, sowie die anderen Optionen (Karte, evtl Navi, usw...).

**Comment by balzer82** [comment]
Daten in 30min Auflösung, falls gewünscht: http://mechlab-engineering.de/downloads/Centrum-Galerie-Belegung-Vorhersage-2015-30min.csv

**Comment by jklmnn** [comment]
Ich hab die Vorhersagen jetzt serverseitig eingebaut. Es sollte jetzt einfach möglich sein, weitere Parkplätze hinzuzufügen.

**Comment by jklmnn** [comment]
Ich schließe das jetzt mal, da die Vorhersage in die API eingegangen ist und das jetzt extern behandelt wird.
