### ISSUE TITLE
Format auf 4" Display

### ISSUE THREAD

**Issue by kiliankoe** [jklmnn/ParkenDD#15]
(800x480px - Nexus S)

Der Text geht einmal rechts raus und die Sterne in der Prognoseansicht sehe ich nicht.

Aufgrund von mangelnder Screenshot Funktionalität dank kaputter Powertaste als *Bildschirmfoto*.

![img_0928](https://cloud.githubusercontent.com/assets/2625584/7473755/a7521a48-f33d-11e4-9c88-d3156c6eefb7.jpg)
![img_0929](https://cloud.githubusercontent.com/assets/2625584/7473759/aa510920-f33d-11e4-8ff1-e2ecade7aa9b.jpg)

**Comment by jklmnn** [comment]
Ich habs erst mal einigermaßen gefixt, sollte mit 0.7.4-test kommen.
Insgesamt bin ich aber mit dem Datepicker und dem Timepicker unzufrieden, weil die riesig sind (keine Ahnung, was sich Google dabei gedacht hat).

**Comment by jklmnn** [comment]
Ist ab 0.7.4-test gefixt. Das UI hab ich für 0.8.0 noch mal ganz überarbeitet und auch von vornherein auf kleineren Displays getestet.
