### ISSUE TITLE
GitHub Organisation

### ISSUE THREAD

**Issue by AltNico** [jklmnn/ParkenDD#27]
Im Moment sind die Projekte von ParkenDD über "ganz GitHub" verstreut. Ich denke, es wäre einfacher, wenn jemand eine Organisation auf GitHub gründet und alle Projekte dort erreichbar sind.

Ich glaube, das wären dann alle Projekte(?):
- https://github.com/jklmnn/ParkenDD
- https://github.com/jklmnn/ParkenDD-Server
- https://github.com/RobTranquillo/parkplaetzeDD
- https://github.com/offenesdresden/ParkAPI
- https://github.com/kiliankoe/ParkenDD
- https://github.com/ubahnverleih/parkenDD

**Comment by AltNico** [comment]
Falls eine Organisation gegründet werden sollte, siehe #28.

**Comment by kiliankoe** [comment]
Bin persönlich dagegen. Abgesehen davon, dass von den gelisteten Projekten nur noch drei funktionieren, wovon bereits eins unter offenesdresden liegt (auch wenn mehr Städte unterstützt werden sollen), wäre das imho nur sinnvoll, wenn zu den jeweiligen Projekten auch Dritte signifikant beitragen. Beim Server ist das der Fall, bei den Apps (zumindest bisher) nicht.

**Comment by jklmnn** [comment]
ParkenDD-Server von mir ist deprecated und wird in dieser Form nicht mehr genutzt.
Außerdem sinf die "ParkenDD" genannten Projekte unterschiedliche Anwendungen für verschiedene Platformen unter dem gleichen Namen.
