### ISSUE TITLE
Projekt umbenennen

### ISSUE THREAD

**Issue by AltNico** [jklmnn/ParkenDD#28]
Im Moment deutet der Name daraufhin, dass in der App nur Parkplätze für Dresden angezeigt werden können.

Falls irgendwann andere Städte unterstützt werden sollten, würde ein universellerer Name vielleicht besser sein.

**Comment by jklmnn** [comment]
Das wurde auch bereits schon im Slack besprochen, und wir sind zu dem Ergebnis gekommen, dass wir den Namen lassen.
Erstens ist momentan die beste Publicity die Lokalpresse im Raum Dresden, da bietet sich ein an Dresden gebundener Name an.  
Zweitens ist das Projekt hier entstanden.  
Drittens sind und werden Features zuerst in Dresden auftauchen und der Hauptaugenmerk wird auf Dresden bleiben.
Und viertens wird später keiner mehr Fragen, was das DD bedeutet, siehe [KDE](https://de.wikipedia.org/wiki/KDE#Geschichte).
