### ISSUE TITLE
Usability -> Sortieren nach Nähe zum aktuellen Standort

### ISSUE THREAD

**Issue by s72785** [jklmnn/ParkenDD#3]
Der Output ist noch nicht nach Entfernung sortiert.
Die reine Triangulierung mit Koordinaten wäre schon eine gute Hilfe.
Berechnung des Fahrweges halte ich mal für etwas übertrieben.

**Comment by jklmnn** [comment]
Standortunterstützung und Entfernungsanzeige eingebaut.
a361578d7ec8fe10d3c3f66ad29f4f45bbfef3a6 / 4353714d432e73cf839252281706167ba4ea1040

**Comment by jklmnn** [comment]
Sortieren nach Entfernung ist ab 12ad29c08077b052c35158c5091007bfe30a12e5 eingebaut.
Die freien Parkplätze werden in #13 behandelt.
