### ISSUE TITLE
Nachhaltigkeit -> Beschreibung des Formates für Server-Output

### ISSUE THREAD

**Issue by s72785** [jklmnn/ParkenDD#4]
Die Daten, die seitens eines Servers benötigt werden wären gut zu wissen um ggf. weitere Server - auch an anderen Orten (sobald man mehrere einstellen kann) zu nutzen.
Eventuell auch beim Namen dahingehend darauf achten, dass die Lokalisierung dem "Marketing" nicht im Wege steht.

**Comment by jklmnn** [comment]
Also, der neue Server unterstützt Metadaten (die noch erweitert werden können, ohne alte Versionen zu beeinflussen). Dazu siehe http://jkliemann.de/parkendd/dev.html  
Und in seit v0.3.1 funktioniert das Abrufen der Metadaten sowie das wechseln des Servers auch.
