### ISSUE TITLE
Proposal for copyrighting 

### ISSUE THREAD

**Issue by beckysophie** [jklmnn/ParkenDD#52]
Hello @jklmnn am an app tester and have little idea on developing. I appreciate your idea about the ParkenDD App and would love to make a contribution to it via making a copywrite for your Readme and make a pull request for you to merge. Kindly inform me, if it's OK by you.  Thanks 

 - becky

**Comment by jklmnn** [comment]
Thanks for your interest in this project.
I'm not sure what you mean exactly by "making a copywrite for your Readme". Generally this project is licensed under the [GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) so you are allowed and required to do what the license implies (see the link).
Feel free to create a pull request here. I will review and merge it if I'm in consent with the changes.

**Comment by beckysophie** [comment]
Oh.... Great..... 


It's kinda a write about the app, FAQs, privacy and policy.... And whatever you desire that should be added

**Comment by jklmnn** [comment]
I currently have no plans to add/modify any of these properties. If you think something needs to be change submit an issue with a specific problem/request or submit a pull request if you already have changes you want to have merged.
