### ISSUE TITLE
Map view doesn't work

### ISSUE THREAD

**Issue by OliverGraetsch** [jklmnn/ParkenDD#54]
On my Oneplus 6 (Android 9), the map view doesn't work. It seems to show my location and the parking spots around with status, but no map. There's only a grid of grey squares. Tried different cities, all wit the same issue.

**Comment by jklmnn** [comment]
Have you allowed storage access? The OSM plugin needs it to cache the tiles (although in theory it should still download them). It could also be a problem with the tile provider. I'll check if I find a better one.

**Comment by OliverGraetsch** [comment]
Yes, I allowed it. Thanks for checking.

**Comment by jklmnn** [comment]
I looked into MapBox but osmdroid doesn't seem to support their styles correctly so there is only a half empty black map available. The current alternatives are
 - Using MapBox' own Android SDK
 - Trying another (possibly multiple) providers with osmdroid

The first one requires a reimplementation of the current map view for the new SDK. The second might require a significant amount of time (and test accounts) without a guarantee that a feasible provider is found. 
In general there don't seem to be real free providers (at least not without breaking terms of service) as the number of free requests is quite low (<25k/month). Also the paid subscriptions are too expensive. Even the smallest packages (25-50k/month) cost ~$100/month which is way too much.

As I lack the time to build a working (and useful) map view and I'm not willing to pay significant amounts of money I'm going to remove this broken feature altogether.
