### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [jklmnn/ParkenDD#56]
You can add Screenshots for F-Droid, too, if you want. 

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by jklmnn** [comment]
Thanks for the info. I have to update the screenshots in the playstore anyway. I have to see when I find time for this which currently is the biggest problem.

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.

**Comment by jklmnn** [comment]
This issues has been fixed with https://github.com/jklmnn/ParkenDD/commit/4db5c7a4976e1fe5c15f5582794f6b0531848b8c.
