### ISSUE TITLE
Alphabetisch sortieren

### ISSUE THREAD

**Issue by RobTranquillo** [jklmnn/ParkenDD#9]
Ein Hinweis von einem Arbeitskollegen, der der App schon mal probiert, dass die Stellplätze alphabetisch organiert gelistet sein sollten, um den gesuchten Platz schnell zu finden.

**Comment by jklmnn** [comment]
Ich habe auch schon mal darüber nachgedacht mehrere Sortiermöglichkeiten anzubieten. Ich denke, das sollte machbar sein.

**Comment by jklmnn** [comment]
Ich habs endlich mal in Angriff genommen, und es ist ab 12ad29c08077b052c35158c5091007bfe30a12e5 drin.
